

const GET_USERS = 'GET_USERS'
const GET_USERS_PENDING ='GET_USERS_PENDING';
const GET_USERS_REJECTED ='GET_USERS_REJECTED';
const GET_USERS_FULFILLED ='GET_USERS_FULFILLED';
const GET_USERS_CLEAR ='GET_USERS_CLEAR';




export {GET_USERS,GET_USERS_PENDING,GET_USERS_REJECTED,GET_USERS_FULFILLED,GET_USERS_CLEAR};